name: generate rust code from assets

on:
  push:
    branches:
      - release

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  generate_rust_code:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenAPI code generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Install AsyncAPI code generator
        run: npm install -g @asyncapi/cli

      - name: checkout main repository
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: build codegen
        run: cargo build

      - name: run codegen and build workspace
        run: cargo run

      - name: list out target rust code
        run: find target/rust -maxdepth 4 -print

      - name: checkout target repository
        uses: actions/checkout@v4
        with:
          repository: kanekoshoyu/exchange-collection-rust
          token: ${{ secrets.PAT }}
          path: exchange-collection-rust

      - name: sync generated crate
        run: |
          rsync -av --exclude=README.md --exclude=.git --remove-source-files target/rust/ exchange-collection-rust/
          find target/rust -type d -empty -delete

      - name: commit and push changes
        run: |
          cd exchange-collection-rust
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          fi
          git commit -m "Automated update of generated crate"
          git pull --rebase origin main || echo "No changes to pull"
          git push origin main
